#
# Makefile.bor,v 1.11 2003/12/21 09:46:42 jwillemsen Exp
#
# Makefile for building the TAO IDL compiler
#

MAKEFILES = TAO_IDL_FE.bor TAO_IDL_BE.bor tao_idl.bor

!include <$(ACE_ROOT)\include\makeinclude\recurse.bor>
