// -*- C++ -*-
//
// $Id$

// ****  Code generated by the The ACE ORB (TAO) IDL Compiler ****
// TAO and the TAO IDL Compiler have been developed by:
//       Center for Distributed Object Computing
//       Washington University
//       St. Louis, MO
//       USA
//       http://www.cs.wustl.edu/~schmidt/doc-center.html
// and
//       Distributed Object Computing Laboratory
//       University of California at Irvine
//       Irvine, CA
//       USA
//       http://doc.ece.uci.edu/
// and
//       Institute for Software Integrated Systems
//       Vanderbilt University
//       Nashville, TN
//       USA
//       http://www.isis.vanderbilt.edu/
//
// Information about TAO is available at:
//     http://www.cs.wustl.edu/~schmidt/TAO.html

// TAO_IDL - Generated from
// be/be_codegen.cpp:427

#ifndef _TAO_IDL_TEST_EXAMPLES_H_
#define _TAO_IDL_TEST_EXAMPLES_H_


#include "test_exampleC.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */

#include "tao/Collocation_Proxy_Broker.h"
#include "tao/PortableServer/PortableServer.h"
#include "tao/PortableServer/Servant_Base.h"

#if defined(_MSC_VER)
#if (_MSC_VER >= 1200)
#pragma warning(push)
#endif /* _MSC_VER >= 1200 */
#pragma warning(disable:4250)
#endif /* _MSC_VER */

#if defined (__BORLANDC__)
#pragma option push -w-rvl -w-rch -w-ccc -w-inl
#endif /* __BORLANDC__ */

// TAO_IDL - Generated from
// be/be_visitor_module/module_sh.cpp:49

namespace POA_Example
{
  
  
  // TAO_IDL - Generated from
  // be/be_visitor_interface/interface_sh.cpp:90
  
  class Calculator;
  typedef Calculator *Calculator_ptr;
  
  class _TAO_Calculator_ThruPOA_Proxy_Impl;
  class _TAO_Calculator_Strategized_Proxy_Broker;
  
  class  Calculator
    : public virtual PortableServer::ServantBase
  {
  protected:
    Calculator (void);
  
  public:
    // Useful for template programming.
    typedef ::Example::Calculator _stub_type;
    typedef ::Example::Calculator_ptr _stub_ptr_type;
    typedef ::Example::Calculator_var _stub_var_type;
    
    Calculator (const Calculator& rhs);
    virtual ~Calculator (void);
    
    virtual CORBA::Boolean _is_a (
        const char* logical_type_id
        ACE_ENV_ARG_DECL_WITH_DEFAULTS
      );
    
    virtual void* _downcast (
        const char* logical_type_id
      );
    
    static void _is_a_skel (
        TAO_ServerRequest &req,
        void *servant,
        void *servant_upcall
        ACE_ENV_ARG_DECL
      );
    
    static void _non_existent_skel (
        TAO_ServerRequest &req,
        void *servant,
        void *servant_upcall
        ACE_ENV_ARG_DECL
      );
    
    static void _interface_skel (
        TAO_ServerRequest &req,
        void *servant,
        void *servant_upcall
        ACE_ENV_ARG_DECL
      );
    
    static void _component_skel (
        TAO_ServerRequest &req,
        void *obj,
        void *servant_upcall
        ACE_ENV_ARG_DECL
      );
    
    virtual void _dispatch (
        TAO_ServerRequest &req,
        void *_servant_upcall
        ACE_ENV_ARG_DECL
      );
    
    ::Example::Calculator *_this (
        ACE_ENV_SINGLE_ARG_DECL_WITH_DEFAULTS
      );
    
    virtual const char* _interface_repository_id (void) const;
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_sh.cpp:45
    
    virtual CORBA::Long add (
        CORBA::Long a,
        CORBA::Long b
      )
      ACE_THROW_SPEC ((
        CORBA::SystemException
      )) = 0;
    
    static void add_skel (
        TAO_ServerRequest &_tao_req,
        void *_tao_servant,
        void *_tao_servant_upcall
        ACE_ENV_ARG_DECL
      );
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_sh.cpp:45
    
    virtual CORBA::Long subtract (
        CORBA::Long a,
        CORBA::Long b
      )
      ACE_THROW_SPEC ((
        CORBA::SystemException
      )) = 0;
    
    static void subtract_skel (
        TAO_ServerRequest &_tao_req,
        void *_tao_servant,
        void *_tao_servant_upcall
        ACE_ENV_ARG_DECL
      );
  };
  
  ///////////////////////////////////////////////////////////////////////
  //               Strategized Proxy Broker Declaration 
  //
  
  // TAO_IDL - Generated from
  // be/be_visitor_interface/strategized_proxy_broker_sh.cpp:36
  
  class  _TAO_Calculator_Strategized_Proxy_Broker
    : public virtual TAO::Collocation_Proxy_Broker
  {
  public: 
    _TAO_Calculator_Strategized_Proxy_Broker (void);
    
    virtual ~_TAO_Calculator_Strategized_Proxy_Broker (void);
    
    TAO::Collocation_Strategy
    get_strategy (
        CORBA::Object_ptr obj
        ACE_ENV_ARG_DECL
      )
      ACE_THROW_SPEC ((CORBA::SystemException));
    
    void
    dispatch (
        CORBA::Object_ptr obj,
        CORBA::Object_out forward_obj,
        TAO::Argument ** args,
        int num_args,
        const char * op,
        size_t op_len,
        TAO::Collocation_Strategy strategy
        ACE_ENV_ARG_DECL
      )
      ACE_THROW_SPEC ((CORBA::Exception));
    
    static _TAO_Calculator_Strategized_Proxy_Broker *
    the_TAO_Calculator_Strategized_Proxy_Broker (void);
  };
  
  //
  //            End Strategized Proxy Broker Declaration 
  ///////////////////////////////////////////////////////////////////////
  
  
  ///////////////////////////////////////////////////////////////////////
  //                    ThruPOA Proxy Impl. Declaration
  //
  
  // TAO_IDL - Generated from
  // be/be_visitor_interface/thru_poa_proxy_impl_sh.cpp:37
  
  class  _TAO_Calculator_ThruPOA_Proxy_Impl
{
public:
  _TAO_Calculator_ThruPOA_Proxy_Impl (void);
  
  virtual ~_TAO_Calculator_ThruPOA_Proxy_Impl (void) {}
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/proxy_impl_xh.cpp:24
  
  static void
  add (
      TAO_Abstract_ServantBase *servant,
      TAO::Argument ** args,
      int num_args
      ACE_ENV_ARG_DECL
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/proxy_impl_xh.cpp:24
  
  static void
  subtract (
      TAO_Abstract_ServantBase *servant,
      TAO::Argument ** args,
      int num_args
      ACE_ENV_ARG_DECL
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
};

//
//                ThruPOA  Proxy Impl. Declaration
///////////////////////////////////////////////////////////////////////

// TAO_IDL - Generated from
// be/be_visitor_module/module_sh.cpp:80

} // module Example

// TAO_IDL - Generated from 
// be/be_codegen.cpp:1097

#include "test_exampleS_T.h"

#if defined (__ACE_INLINE__)
#include "test_exampleS.i"
#endif /* defined INLINE */

#if defined(_MSC_VER) && (_MSC_VER >= 1200)
#pragma warning(pop)
#endif /* _MSC_VER */

#if defined (__BORLANDC__)
#pragma option pop
#endif /* __BORLANDC__ */

#endif /* ifndef */
