// -*- C++ -*-
//
// $Id$

// ****  Code generated by the The ACE ORB (TAO) IDL Compiler ****
// TAO and the TAO IDL Compiler have been developed by:
//       Center for Distributed Object Computing
//       Washington University
//       St. Louis, MO
//       USA
//       http://www.cs.wustl.edu/~schmidt/doc-center.html
// and
//       Distributed Object Computing Laboratory
//       University of California at Irvine
//       Irvine, CA
//       USA
//       http://doc.ece.uci.edu/
// and
//       Institute for Software Integrated Systems
//       Vanderbilt University
//       Nashville, TN
//       USA
//       http://www.isis.vanderbilt.edu/
//
// Information about TAO is available at:
//     http://www.cs.wustl.edu/~schmidt/TAO.html

// TAO_IDL - Generated from
// be/be_codegen.cpp:339


#include "test_exampleC.h"
#include "tao/Exception_Data.h"
#include "tao/Invocation_Adapter.h"
#include "tao/Object_T.h"
#include "tao/Typecode.h"
#include "tao/Any_Impl_T.h"
#include "tao/Basic_Arguments.h"
#include "ace/OS_NS_string.h"

#if defined (__BORLANDC__)
#pragma option -w-rvl -w-rch -w-ccc -w-aus -w-sig
#endif /* __BORLANDC__ */

#if !defined (__ACE_INLINE__)
#include "test_exampleC.i"
#endif /* !defined INLINE */

// TAO_IDL - Generated from
// be/be_visitor_arg_traits.cpp:62

// Arg traits specializations.
namespace TAO
{
}


// TAO_IDL - Generated from
// be/be_visitor_interface/interface_cs.cpp:60

// Traits specializations for Example::Calculator.

ACE_TEMPLATE_CLASS_MEMBER_SPECIALIZATION
Example::Calculator_ptr
TAO::Objref_Traits<Example::Calculator>::tao_duplicate (
    Example::Calculator_ptr p
  )
{
  return Example::Calculator::_duplicate (p);
}

ACE_TEMPLATE_CLASS_MEMBER_SPECIALIZATION
void
TAO::Objref_Traits<Example::Calculator>::tao_release (
    Example::Calculator_ptr p
  )
{
  CORBA::release (p);
}

ACE_TEMPLATE_CLASS_MEMBER_SPECIALIZATION
Example::Calculator_ptr
TAO::Objref_Traits<Example::Calculator>::tao_nil (void)
{
  return Example::Calculator::_nil ();
}

ACE_TEMPLATE_CLASS_MEMBER_SPECIALIZATION
CORBA::Boolean
TAO::Objref_Traits<Example::Calculator>::tao_marshal (
    Example::Calculator_ptr p,
    TAO_OutputCDR & cdr
  )
{
  return p->marshal (cdr);
}

// Function pointer for collocation factory initialization.
TAO::Collocation_Proxy_Broker * 
(*Example__TAO_Calculator_Proxy_Broker_Factory_function_pointer) (
    CORBA::Object_ptr obj
  ) = 0;

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

CORBA::Long Example::Calculator::add (
    CORBA::Long a,
    CORBA::Long b
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
  ))
{
  if (!this->is_evaluated ())
    {
      ACE_NESTED_CLASS (CORBA, Object)::tao_object_initialize (this);
    }
  
  if (this->the_TAO_Calculator_Proxy_Broker_ == 0)
    {
      Example_Calculator_setup_collocation (
          this->ACE_NESTED_CLASS (CORBA, Object)::_is_collocated ()
        );
    }
  
  ACE_DECLARE_NEW_CORBA_ENV;
  TAO::Arg_Traits<CORBA::Long>::ret_val _tao_retval;
  TAO::Arg_Traits<CORBA::Long>::in_arg_val _tao_a (a);
  TAO::Arg_Traits<CORBA::Long>::in_arg_val _tao_b (b);
  
  TAO::Argument *_tao_signature [] =
    {
      &_tao_retval,
      &_tao_a,
      &_tao_b
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _tao_signature,
      3,
      "add",
      3,
      this->the_TAO_Calculator_Proxy_Broker_
    );
  
  _tao_call.invoke (0, 0 ACE_ENV_ARG_PARAMETER);
  ACE_CHECK_RETURN (_tao_retval.excp ());
  
  return _tao_retval.retn ();
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

CORBA::Long Example::Calculator::subtract (
    CORBA::Long a,
    CORBA::Long b
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
  ))
{
  if (!this->is_evaluated ())
    {
      ACE_NESTED_CLASS (CORBA, Object)::tao_object_initialize (this);
    }
  
  if (this->the_TAO_Calculator_Proxy_Broker_ == 0)
    {
      Example_Calculator_setup_collocation (
          this->ACE_NESTED_CLASS (CORBA, Object)::_is_collocated ()
        );
    }
  
  ACE_DECLARE_NEW_CORBA_ENV;
  TAO::Arg_Traits<CORBA::Long>::ret_val _tao_retval;
  TAO::Arg_Traits<CORBA::Long>::in_arg_val _tao_a (a);
  TAO::Arg_Traits<CORBA::Long>::in_arg_val _tao_b (b);
  
  TAO::Argument *_tao_signature [] =
    {
      &_tao_retval,
      &_tao_a,
      &_tao_b
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _tao_signature,
      3,
      "subtract",
      8,
      this->the_TAO_Calculator_Proxy_Broker_
    );
  
  _tao_call.invoke (0, 0 ACE_ENV_ARG_PARAMETER);
  ACE_CHECK_RETURN (_tao_retval.excp ());
  
  return _tao_retval.retn ();
}

Example::Calculator::Calculator (int collocated)
 : the_TAO_Calculator_Proxy_Broker_ (0)
{
  this->Example_Calculator_setup_collocation (collocated);
}

void
Example::Calculator::Example_Calculator_setup_collocation (int collocated)
{
  if (collocated)
    {
      this->the_TAO_Calculator_Proxy_Broker_ =
        ::Example__TAO_Calculator_Proxy_Broker_Factory_function_pointer (this);
    }
}

Example::Calculator::~Calculator (void)
{}

void 
Example::Calculator::_tao_any_destructor (void *_tao_void_pointer)
{
  Calculator *_tao_tmp_pointer =
    ACE_static_cast (Calculator *, _tao_void_pointer);
  CORBA::release (_tao_tmp_pointer);
}

Example::Calculator_ptr
Example::Calculator::_narrow (
    CORBA::Object_ptr _tao_objref
    ACE_ENV_ARG_DECL
  )
{
  return
    TAO::Narrow_Utils<Calculator>::narrow (
        _tao_objref,
        "IDL:Example/Calculator:1.0",
        Example__TAO_Calculator_Proxy_Broker_Factory_function_pointer
        ACE_ENV_ARG_PARAMETER
      );
}

Example::Calculator_ptr
Example::Calculator::_unchecked_narrow (
    CORBA::Object_ptr _tao_objref
    ACE_ENV_ARG_DECL
  )
{
  return
    TAO::Narrow_Utils<Calculator>::unchecked_narrow (
        _tao_objref,
        "IDL:Example/Calculator:1.0",
        Example__TAO_Calculator_Proxy_Broker_Factory_function_pointer
        ACE_ENV_ARG_PARAMETER
      );
}

Example::Calculator_ptr
Example::Calculator::_duplicate (Calculator_ptr obj)
{
  if (! CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  
  return obj;
}

CORBA::Boolean
Example::Calculator::_is_a (
    const char *value
    ACE_ENV_ARG_DECL
  )
{
  if (
      !ACE_OS::strcmp (
          (char *)value,
          "IDL:Example/Calculator:1.0"
        ) ||
      !ACE_OS::strcmp (
          (char *)value,
          "IDL:omg.org/CORBA/Object:1.0"
        )
     )
    {
      return 1; // success using local knowledge
    }
  else
    {
      return this->ACE_NESTED_CLASS (CORBA, Object)::_is_a (
          value
          ACE_ENV_ARG_PARAMETER
        );
    }
}

const char* Example::Calculator::_interface_repository_id (void) const
{
  return "IDL:Example/Calculator:1.0";
}

CORBA::Boolean
Example::Calculator::marshal (TAO_OutputCDR &cdr)
{
  return (cdr << this);
}

// TAO_IDL - Generated from
// be/be_visitor_typecode/typecode_defn.cpp:284

static const CORBA::Long _oc_Example_Calculator[] =
{
    TAO_ENCAP_BYTE_ORDER, // byte order
  27,
  ACE_NTOHL (0x49444c3a), 
  ACE_NTOHL (0x4578616d), 
  ACE_NTOHL (0x706c652f), 
  ACE_NTOHL (0x43616c63), 
  ACE_NTOHL (0x756c6174), 
  ACE_NTOHL (0x6f723a31), 
  ACE_NTOHL (0x2e300000),  // repository ID = IDL:Example/Calculator:1.0
    11,
  ACE_NTOHL (0x43616c63), 
  ACE_NTOHL (0x756c6174), 
  ACE_NTOHL (0x6f720000),  // name = Calculator
  };

static CORBA::TypeCode _tc_TAO_tc_Example_Calculator (
    CORBA::tk_objref,
    sizeof (_oc_Example_Calculator),
    (char *) &_oc_Example_Calculator,
    0,
    sizeof (Example::Calculator)
  );

namespace Example
{
  ::CORBA::TypeCode_ptr _tc_Calculator =
    &_tc_TAO_tc_Example_Calculator;
}

// TAO_IDL - Generated from
// be/be_visitor_interface/any_op_cs.cpp:50

ACE_TEMPLATE_SPECIALIZATION
CORBA::Boolean
TAO::Any_Impl_T<Example::Calculator>::to_object (
    CORBA::Object_ptr &_tao_elem
  ) const
{
  _tao_elem = CORBA::Object::_duplicate (this->value_);
  return 1;
}

// Copying insertion.
void
operator<<= (
    CORBA::Any &_tao_any,
    Example::Calculator_ptr _tao_elem
  )
{
  Example::Calculator_ptr _tao_objptr =
    Example::Calculator::_duplicate (_tao_elem);
  _tao_any <<= &_tao_objptr;
}

// Non-copying insertion.
void
operator<<= (
    CORBA::Any &_tao_any,
    Example::Calculator_ptr *_tao_elem
  )
{
  TAO::Any_Impl_T<Example::Calculator>::insert (
      _tao_any,
      Example::Calculator::_tao_any_destructor,
      Example::_tc_Calculator,
      *_tao_elem
    );
}

CORBA::Boolean
operator>>= (
    const CORBA::Any &_tao_any,
    Example::Calculator_ptr &_tao_elem
  )
{
  return
    TAO::Any_Impl_T<Example::Calculator>::extract (
        _tao_any,
        Example::Calculator::_tao_any_destructor,
        Example::_tc_Calculator,
        _tao_elem
      );
}

// TAO_IDL - Generated from
// be/be_visitor_interface/cdr_op_cs.cpp:63

CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const Example::Calculator_ptr _tao_objref
  )
{
  CORBA::Object_ptr _tao_corba_obj = _tao_objref;
  return (strm << _tao_corba_obj);
}

CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    Example::Calculator_ptr &_tao_objref
  )
{
  CORBA::Object_var obj;
  
  if ((strm >> obj.inout ()) == 0)
    {
      return 0;
    }
  
  typedef ::Example::Calculator RHS_SCOPED_NAME;
  
  // Narrow to the right type.
  _tao_objref =
    TAO::Narrow_Utils<RHS_SCOPED_NAME>::unchecked_narrow (
        obj.in (),
        Example__TAO_Calculator_Proxy_Broker_Factory_function_pointer
      );
    
  return 1;
}

